const initialState = {
    dateTime: '',
    date: '',
    office: '',
    responsible: '',
    email: '',
    phone: '',
    loanAmount: '',
    loanTerm: '',
    loanRate: '',
    ElectricRegistration_IsChecked: false,
    taxDeclarationData_IsChecked: false,
    workCertificateData_IsChecked: false,
    salaryTransactionStatement_IsChecked: false,
    pdfTaxStatement_IsChecked: false,
    notarizedMarriageContract_IsChecked: false,
    spouseNotaryConsent_IsChecked: false,
    borrowerSingleDeclaration_IsChecked: false,
    maritalStatusDeclaration_IsChecked: false,
    notaryConsentSpouse_IsChecked: false,
    marriageContract_IsChecked: false,
    notaryTrustDocument_IsChecked: false,
    expertContingentConditions: '',
    inputClientName: '',
    selectedOffice: null,
    selectedContact: null,
    creditAgreementNumber: '',
    
};

export default initialState
